(function(a,m,f){"use strict";const{sendBotMessage:o}=m.findByProps("sendBotMessage"),y="https://discord.com/channels/1015931589865246730/1092643779523121262";function w(n){return n.replace(/\[(.*?)\]/g,(i,e)=>(e=e.trim(),e))}function b(n){const i="https://www.urbandictionary.com/define.php?term=";return n.replace(/\[(.*?)\]/g,(e,t)=>(t=t.trim(),`[${t}](<${i+encodeURIComponent(t)}>)`))}function l(n){return`> ${n.replaceAll(`
`,`
> `)}`}async function g(n,i){try{const e=new Map(n.map(h=>[h.name,h])),t=e.get("word").value.trim(),k=encodeURIComponent(t),_=`https://api.urbandictionary.com/v0/define?term=${k}`,s=await fetch(_),v=await s.json(),M=e.get("inline_links")?.value||!1,d=v.list?.[0],c=d?.definition;if(!c)return o(i.channel.id,`No definition found for \`${t.replaceAll("`","`\u{E0134}")}\`${s.status!==200?` (${s.status})`:""}`);const p=d.permalink;let r=`__Definition for **\`${d.word}\`**__`;if(M?r+=` ([source](${p}))
${l(b(c))}`:r+=`
${l(w(c))}

Source: <${p}>`,e.get("ephemeral")?.value===!1)return{content:r};o(i.channel.id,r)}catch(e){alert(e.stack),console.error(e),o(i.channel.id,`\`\`\`js
${e.stack}\`\`\`An error has occurred while processing the </urban:0> command
Send the error in ${y}.`)}}let u;var $={onLoad:()=>{u=f.registerCommand({name:"urban",displayName:"urban",description:"Search urban dictionary",displayDescription:"Search urban dictionary",options:[{name:"word",displayName:"word",description:"The word you want the definition for",displayDescription:"The word you want the definition for",required:!0,type:3},{name:"ephemeral",displayName:"ephemeral",description:"Make outputs only be seen by you (default: true)",displayDescription:"Make outputs only be seen by you (default: true)",type:5,required:!1},{name:"inline_links",displayName:"inline_links",description:"Makes the [highlighted] words pressable (default: false)",displayDescription:"Makes the [highlighted] words pressable (default: false)",type:5,required:!1}],execute:g,applicationId:-1,inputType:1,type:1})},onUnload:()=>{u()}};return a.default=$,Object.defineProperty(a,"__esModule",{value:!0}),a})({},vendetta.metro,vendetta.commands);
